name: md2pdf-webserver
version: 0.0.8
summary: md2pdf server package, to render Markdown text from clients into a pretty PDF
description: |
    md2pdf is a little project that aims to make it easy to produce
    professional-looking PDF documents from Markdown files via a LaTeX template
    and the help of Pandoc.

    With with an appropriate template, LaTeX PDF output is undeniably the prettiest-
    looking way to create documents. But, learning LaTeX is hard. Markdown
    is much easier to use, and when used with Pandoc can still produce superb PDF
    documents. md2pdf makes it simple to manage having the right LaTeX templates
    and configuration across a whole team, by using a central server to do the PDF
    generation and then share the result with those who need it.

    This is the server application - it might take some substatial configuration
    to get running correctly. See https://github.com/seanlano/md2pdf-webserver
    for more information.

icon: icon.svg
grade: devel
confinement: strict

parts:
  md2pdf-webserver:
    plugin: python
    python-version: python3
    source-type: git
    source: https://github.com/seanlano/md2pdf-webserver.git
    source-tag: v0.0.8
    requirements: requirements.txt
    stage-packages:
      - librsvg2-bin
      - libc6
      - libstdc++6
      - binutils
      - wget
      - fontconfig
      - grep
      - perl-base
      - perl
      - gnupg2
      - locales
      - tar
      - gzip
      - bzip2
      - fonts-dejavu
      - fonts-hack-ttf
      - fonts-freefont-ttf
      - fonts-liberation
      - fonts-lyx
      - fonts-mathjax
      - fonts-opensymbol
      - fonts-sil-gentium
      - fonts-sil-gentium-basic
      - ttf-bitstream-vera
      - ttf-ubuntu-font-family
      - ghostscript

  texlive-installer:
    plugin: nil
    source: .
    build-packages:
      - wget
    override-build: |
      wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
      mkdir -p $SNAPCRAFT_PART_INSTALL/snap
      cp install-tl-unx.tar.gz $SNAPCRAFT_PART_INSTALL/snap/

  static-content:
      plugin: nil
      source: https://github.com/seanlano/md2pdf-webserver.git
      source-tag: v0.0.8
      override-build: |
        mkdir -p $SNAPCRAFT_PART_INSTALL/snap
        cp -r example-static/ $SNAPCRAFT_PART_INSTALL/snap/
        cp setup-chroot.sh $SNAPCRAFT_PART_INSTALL/snap/
        cp md2pdf-texlive.profile $SNAPCRAFT_PART_INSTALL/snap/
        mkdir -p $SNAPCRAFT_PART_INSTALL/snap/html
        cp index.html $SNAPCRAFT_PART_INSTALL/snap/html
        cp style.css $SNAPCRAFT_PART_INSTALL/snap/html

  pandoc:
    plugin: nil
    source: .
    build-packages:
      - wget
      - tar
    override-build: |
      wget https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-linux.tar.gz -O pandoc.tar.gz
      tar xvf pandoc.tar.gz --strip-components 1 --directory $SNAPCRAFT_PART_INSTALL/

  pandoc-crossref:
    plugin: nil
    source: .
    build-packages:
      - wget
      - tar
    override-build: |
      wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.2.1/linux-ghc84-pandoc22.tar.gz -O pandoc-crossref.tar.gz
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      tar xvf pandoc-crossref.tar.gz --directory $SNAPCRAFT_PART_INSTALL/bin

apps:
    md2pdf-webserver:
        command: md2pdf_webserver
        plugs: [network-bind]
    daemon:
        command: md2pdf_webserver --run
        daemon: simple
        restart-condition: always
        stop-timeout: 90s
        plugs: [network-bind]

environment:
    LC_ALL: C
